# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI Github

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: 'maven'
    - name: Set up MySQL
      uses: shogo82148/actions-setup-mysql@v1
      with:
        mysql-version: '8.0'
    - run: mysql -uroot -h127.0.0.1 -e "CREATE DATABASE guests CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;"
    - run: mysql -uroot -h127.0.0.1 -e "CREATE USER 'guests'@'localhost' IDENTIFIED BY 'secret';";
    - run: mysql -uroot -h127.0.0.1 -e "GRANT ALL privileges ON guests.* TO 'guests'@'localhost';"
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Codecov
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
        verbose: true